import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Book sidebar: wrap autogenerated items in a root category with a generated index at /docs/book
  bookSidebar: [
    {
      type: 'category',
      label: 'Book',
      link: {
        type: 'generated-index',
        title: 'Beyond the Browser — Book',
        description: '本书目录（自动生成）',
      },
      items: [{type: 'autogenerated', dirName: 'book'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  bookSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};

export default sidebars;
