import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 顶级直接使用 wasm 目录的自动生成结构（顶层标签由 docs/wasm/_category_.json 控制）
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'wasm' }],
};

export default sidebars;