[package]
name = "http_spin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spin-sdk = { version = "3.0.1", default-features = false, features = ["http"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
