[package]
name = "inc_component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.36.0"

[package.metadata.component]
wit-path = "wit"
world = "inc-world"
