name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "src/**"
      - "docusaurus.config.ts"
      - "sidebars.ts"
      - "package.json"
      - "yarn.lock"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  contents: write # required for pushing to gh-pages

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node }}"
          cache: "yarn"

      - name: Install Yarn (classic)
        run: npm i -g yarn@1.22.22

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn --silent typecheck || true

      - name: Build website
        run: bash -lc 'STRICT_LINKS=0 yarn build'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          force_orphan: true
